# Generated by Django 6.0.3 on 2026-05-07 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Samsung', 'Samsung'), ('Apple', 'Apple'), ('Vivo', 'Vivo'), ('Oppo', 'Oppo'), ('OnePlus', 'OnePlus'), ('Redmi', 'Redmi'), ('IQOO', 'IQOO')], default='samsung', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='products/'),
        ),
    ]
