# Generated by Django 6.0.3 on 2026-06-16 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_product_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Samsung', 'Samsung'), ('Apple', 'Apple'), ('OnePlus', 'OnePlus'), ('Redmi', 'Redmi'), ('IQOO', 'IQOO'), ('Realme', 'Realme'), ('Google', 'Google'), ('ASUS', 'ASUS'), ('Vivo', 'Vivo'), ('Oppo', 'Oppo')], max_length=100),
        ),
    ]
